services:
  - type: web
    name: career-guide-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: CLIENT_ORIGIN
        sync: false 